version: '3.8'
services:
  fx-deals-app:
    build: .
    restart: on-failure
    container_name: fx-deals-app
    ports:
      - '8080:8080'
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Rand
      MYSQL_DB: clustered_data_warehouse
      MYSQL_HOST: mysqldb
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: Rand
      MYSQL_DATABASE: clustered_data_warehouse
      MYSQL_ROOT_USERNAME: root
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=Rand" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: on-failure